#!/bin/bash

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd $REPO_ROOT

function run_test {
    if git rev-parse --verify HEAD >/dev/null 2>&1 ; then
        head="HEAD"
    else
        # First commit, use an empty tree
        head="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
    fi
    #git diff-index --check --cached "${head}" --
    files=`git diff-index --cached --name-only "${head}"`
    error=""
    for file in $files
    do
        pattern="^+[ ]*"$'\t'"[ ]*"
        res=`git diff --cached $file | grep -n -G "^+[ ]*"$'\t'"[ ]*"`
        if [ -n "$res" ] ; then
            echo "Pre-Commit Check: Found Tab characters at start of following lines in $file"
            echo
            echo "$res"
            echo
            error="True"
        fi
    done

    if [ -n "$error" ]; then
        echo "Commit Aborted"
        exit 1
    else
        exit 0
    fi

}

case "${1}" in
    --about )
        echo "Check for introduced trailing whitespace or an indent that uses a space before a tab."
        ;;
    * )
        run_test
        ;;
esac


